### PR TITLE
Remove Cypress based UI tests

### PR DESCRIPTION
**Pull request by ximon18**
As the new Krill UI 2.0 has its own test suite.

Note that this PR also removes the OIDC mock and related tests for which we have no replacement at present, especially for the cases where incorrect OIDC provider behaviour or incorrectly configured OIDC responses are tested. Manual testing will suffice for now, and later we should perhaps factor out the OIDC stuff entirely to a separate crate complete with its own tests, and not depend on a real user agent (i.e. Cypress driven FireFox/Chrome as it is now) for integration testing but test more at the unit test level.

### CODE REVIEW

**Review by timbru — APPROVED** [review]
Looks good to me. Indeed.. it would be good to split Krill into sub-crates now that it's mostly mature.

This should also help to bring down compilation times, and allow us to test things in isolation.

**Comment by ximon18** [comment]
@timbru: This PR only makes sense to merge if the pending Krill UI 2.0 PRs are merged so I won't merge it yet unless you're sure you'll merge the Krill UI 2.0 PRs and want this one closed to keep things organized?

**Comment by timbru** [comment]
@ximon18 makes sense.. I will go over the Krill UI 2.0/2.1 PRs - I hope we can merge them.

**Comment by timbru** [comment]
Merging - Krill UI 2.0 will be merged shortly.

**Pull request merged**
